"""Create doctor_reports table

Revision ID: 32fe2b14246a
Revises: e8971449038a
Create Date: 2025-07-16 14:47:00.825022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32fe2b14246a'
down_revision: Union[str, None] = 'e8971449038a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alembic_version')
    op.drop_constraint('appointments_patient_id_fkey', 'appointments', type_='foreignkey')
    op.drop_constraint('appointments_doctor_id_fkey', 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'users', ['patient_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'appointments', 'users', ['doctor_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('doctor_reports_doctor_id_fkey', 'doctor_reports', type_='foreignkey')
    op.create_foreign_key(None, 'doctor_reports', 'users', ['doctor_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('doctor_specializations_doctor_id_fkey', 'doctor_specializations', type_='foreignkey')
    op.create_foreign_key(None, 'doctor_specializations', 'users', ['doctor_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('periodic_task_user_id_fkey', 'periodic_task', type_='foreignkey')
    op.create_foreign_key(None, 'periodic_task', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'periodic_task', schema='public', type_='foreignkey')
    op.create_foreign_key('periodic_task_user_id_fkey', 'periodic_task', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'doctor_specializations', schema='public', type_='foreignkey')
    op.create_foreign_key('doctor_specializations_doctor_id_fkey', 'doctor_specializations', 'users', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'doctor_reports', schema='public', type_='foreignkey')
    op.create_foreign_key('doctor_reports_doctor_id_fkey', 'doctor_reports', 'users', ['doctor_id'], ['id'])
    op.drop_constraint(None, 'appointments', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'appointments', schema='public', type_='foreignkey')
    op.create_foreign_key('appointments_doctor_id_fkey', 'appointments', 'users', ['doctor_id'], ['id'])
    op.create_foreign_key('appointments_patient_id_fkey', 'appointments', 'users', ['patient_id'], ['id'])
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_pkc')
    )
    # ### end Alembic commands ###
